"""empty message

Revision ID: 3f174cac3fd3
Revises: None
Create Date: 2018-03-21 16:08:54.024578

"""

# revision identifiers, used by Alembic.
revision = '3f174cac3fd3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
